#!/usr/bin/env sh

. ./lib.sh

if [ -f "${BACKUP_CONFIG_YAML}" ]; then
  echo "🤖 Setting up crontab from '${BACKUP_CONFIG_YAML}'"
  yq 'to_entries | .[] | "\(.value.schedule // env(DEFAULT_SCHEDULE)) /app/backup \(.key)"' "${BACKUP_CONFIG_YAML}" >> /etc/crontabs/root
else
  echo "🤖 assuming a crontab is mounted at '/etc/crontabs/root'"
fi

echo "🤖 Current crontab:"
cat /etc/crontabs/root

echo "🤖 Starting crond..."
exec crond -f -d 8 -L /dev/stdout -l 8